gateway:
  logLevel:
  image: "subsquid/query-gateway:1.0.0-rc3"
  # List of LibP2p keys base64 encoded.
  # For each key 1 replica of the gateway will be created and traffic will be routed between them.
  libp2p_private_keys: []
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: "0.5"
      memory: "256M"
  podMonitor:
    enabled: false

# Expose the gateway service to the internet
ingress:
  class: "nginx"
  host:

# RPC configuration
rpc:
  network: mainnet
  url: https://arb1.arbitrum.io/rpc
  l1_url: https://ethereum.publicnode.com

# Network configuration
network:
  logs_collector_peer_id: "12D3KooWFnRhNqgsKtsDDhsozaWuyrTvtQA2Eu4XWvSPRd4UZynd"
  boot_nodes: >-
    12D3KooW9tLMANc4Vnxp27Ypyq8m8mUv45nASahj3eSnMbGWSk1b /dns4/mainnet.subsquid.io/udp/22445/quic-v1,
    12D3KooWEhPC7rsHAcifstVwJ3Cj55sWn7zXWuHrtAQUCGhGYnQz /dns4/mainnet.subsquid.io/udp/22446/quic-v1,
    12D3KooWS5N8ygU6fRy4EZtzdHf4QZnkCaZrwCha9eYKH3LwNvsP /dns4/mainnet.subsquid.io/udp/32445/quic-v1
  mtu_discovery_max: 1412

# List of datasets served by gateway
datasets:
  ethereum-mainnet: "czM6Ly9ldGhlcmV1bS1tYWlubmV0LTE"
