{{- if .Values.gateway.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: enabled
  name: gateway-scraper
spec:
  selector:
    matchLabels:
      app: gateway
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      port: http
{{- end }}